apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
      - name: user-server
        image: gongyitong/us:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-server-service
spec:
  type: NodePort
  selector:
    app: user-server
  ports:
  - port: 8080
    nodePort: 30003
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci-server
  template:
    metadata:
      labels:
        app: fibonacci-server
    spec:
      containers:
      - name: fibonacci-server
        image: gongyitong/fs:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-server-service
spec:
  type: NodePort
  selector:
    app: fibonacci-server
  ports:
  - port: 9090
    nodePort: 30002
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authoritative-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authoritative-server
  template:
    metadata:
      labels:
        app: authoritative-server
    spec:
      containers:
      - name: authoritative-server
        image: gongyitong/as:latest
        ports:
        - containerPort: 53533
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: authoritative-server-service
spec:
  type: NodePort
  selector:
    app: authoritative-server
  ports:
  - port: 53533
    nodePort: 30001
    protocol: UDP
